Update SubDomainEnum

diff --git a/SubDomainEnum b/SubDomainEnum
--- a/SubDomainEnum
+++ b/SubDomainEnum
@@ -2,23 +2,33 @@
 
 # Check if the user provided the required arguments
 if [ "$#" -lt 2 ] || [ "$1" != "-f" ]; then
-    echo "Usage: $(basename $0) -f <path_to_file> [-n <path_to_notarget_file>]"
+    echo "Usage: $(basename $0) -f <path_to_file> [-not_in_scope <path_to_not_in_scope_file>] --subdomain-wordlist <path_to_amass_wordlist> --nuclei-templates <path_to_nuclei_templates> --ffuf-wordlist <path_to_wordlist_directories>"
     exit 1
 fi
 
-# Read the input file from the command-line arguments
-Filename="$2"
+# Parse the arguments
+while [ "$#" -gt 0 ]; do
+    case $1 in
+        -f) Filename="$2"; shift ;;
+        -not_in_scope) NotargetFile="$2"; shift ;;
+        --subdomain-wordlist) SUBDOMAIN_WORDLIST="$2"; shift ;;
+        --nuclei-templates) NUCLEI_TEMPLATES="$2"; shift ;;
+        --ffuf-wordlist) FFUF_WORDLIST="$2"; shift ;
+        *) echo "Unknown parameter passed: $1"; exit 1 ;;
+    esac
+    shift
+done
 
-# Check if the notarget file is provided
-if [ "$#" -eq 4 ] && [ "$3" == "-n" ]; then
-    NotargetFile="$4"
-else
-    NotargetFile=""
+if [ -z "$Filename" ] || [ -z "$SUBDOMAIN_WORDLIST" ] || [ -z "$NUCLEI_TEMPLATES" ] || [ -z "$FFUF_WORDLIST" ]; then
+    echo "Error: One or more required arguments are missing."
+    echo "Usage: $(basename $0) -f <path_to_file> [--not_in_scope <path_to_not_in_scope_file>] --subdomain-wordlist <path_to_subdomain_wordlist> --nuclei-templates <path_to_nuclei_templates> --ffuf-wordlist <path_to_ffuf_wordlist>"
+    exit 1
 fi
 
 mkdir aquatone
+mkdir ffuf
 echo "Running subdomain enumeration..." | notify -silent
-while read line; do amass enum -d $line -w /root/data/manual/2m-subdomains.txt -o amass1.txt; done < $Filename
+while read line; do amass enum -d $line -w $SUBDOMAIN_WORDLIST -o amass1.txt; done < $Filename
 while read line; do amass enum -d $line -o amass2.txt; done < $Filename &
 while read line; do assetfinder --subs-only $line | tee -a assetfinder.txt; done < $Filename &
 while read line; do subfinder -v -d $line -o subfinder.txt; done < $Filename
@@ -37,12 +47,12 @@ rm All_Subdomains_temp.txt
 echo "Scanning live web servers with httpx..." | notify -silent
 cat All_Subdomains.txt | httpx -p 80,81,300,443,591,593,832,981,1010,1311,2082,2087,2095,2096,2480,3000,3128,3333,4243,4567,4711,4712,4993,5000,5104,5108,5800,6543,7000,7396,7474,8000,8001,8008,8014,8042,8069,8080,8081,8088,8090,8091,8118,8123,8172,8222,8243,8280,8281,8333,8443,8500,8834,8880,8888,8983,9000,9043,9060,9080,9090,9091,9200,9443,9800,9981,12443,16080,18091,18092,20720,28017 -o httpx.txt
 cat All_Subdomains.txt | httpx -p 80,81,300,443,591,593,832,981,1010,1311,2082,2087,2095,2096,2480,3000,3128,3333,4243,4567,4711,4712,4993,5000,5104,5108,5800,6543,7000,7396,7474,8000,8001,8008,8014,8042,8069,8080,8081,8088,8090,8091,8118,8123,8172,8222,8243,8280,8281,8333,8443,8500,8834,8880,8888,8983,9000,9043,9060,9080,9090,9091,9200,9443,9800,9981,12443,16080,18091,18092,20720,28017 -sc -td -server -title -location -o httpx2.txt &
-cat httpx.txt | for i in $(cat httpx.txt); do DOMAIN=$(echo $i | unfurl format %d); ffuf -u $i/FUZZ -w /root/data/manual/raft-large-directories.txt -fc 404 -recursion -r -o ${DOMAIN}_ffuf.txt; done &
-nuclei -t /root/nuclei-templates/ -l httpx.txt -o nuclei.txt & 
+nuclei -t $NUCLEI_TEMPLATES -l httpx.txt -o nuclei.txt & 
 cat httpx.txt | aquatone -ports xlarge -out aquatone/ &
 cat httpx.txt | gau --subs --verbose --blacklist png,jpg,gif,jpeg,swf,woff,svg,css --o gau.txt &
 katana -list httpx.txt -jc -kf -aff -ef png,jpg,gif,jpeg,swf,woff,svg,css -o katana.txt
 wait
 cat gau.txt katana.txt | sort -u | tee -a allUrls.txt | httpx -mc 200,403 -o LiveUrls.txt
-nuclei -t /root/nuclei-templates/ -l LiveUrls.txt -es info -o nucleiAll.txt
+nuclei -t $NUCLEI_TEMPLATES -l LiveUrls.txt -es info -o nucleiAll.txt &
+cat httpx.txt | for i in $(cat httpx.txt); do DOMAIN=$(echo $i | unfurl format %d); ffuf -u $i/FUZZ -w $FFUF_WORDLIST -fc 404 -recursion -r -ac -rate 10 -of ffuf/${DOMAIN}_ffuf.html -o ffuf/${DOMAIN}_ffuf.txt; done &
 echo "Recon is Done" | notify -silent
